name: build

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: install gcc 
        run: apt install gcc -y
      -
        name: build 
        run: go build

        
