name: build

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: [ubuntu-latest,windows-latest]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: install gcc 
        run: sudo apt install gcc -y
      -
        name: build 
        run: pwd && go build

        
