name: build

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: install gcc 
        run: sudo apt install gcc -y
      -
        name: build 
        run: go build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: n8maninger/action-golang-test@v1
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Run GolangCI-Lint Action by building from repository
      - uses: matoous/golangci-lint-action@v1.1.0

        
